### ISSUE TITLE
Unable to run program correctly

### ISSUE THREAD

**Issue by li-shuang-git** [shubhamgpt007/CrisisKAN#1]
Dear authors,

Thanks for providing us this github repo and work.

1. You used a non-existent requirements. txt file in the setup.sh file, but you provided the requirements. yml file, and I successfully downloaded the relevant dependency packages
2. I encountered an error while running the program: `No such file or directory: '/ The datasets/CrisisMMD_v2.0/crisismmd_datasplit1all/wiki_settingA/task-informative_text_img_train. tsv '`conflicts with the directory structure of the project. Simply put, there is no wiki_settingA folder. I hope you can provide the correct project structure or answer my questions

Again thanks for your great work.

**Comment by shubhamgpt007** [comment]
Hi,
Thanks for pointing out the issues. I have updated the repository with relevant changes. You can try it now and in case of any further issue, you can post it here.

**Comment by li-shuang-git** [comment]
While executing the program, I still encountered the following error message:`Traceback (most recent call last):
  File "/autodl-fs/data/CrisisKan/main.py", line 80, in <module>
    train_set.initialize(opt, phase='train', cat='all',
  File "/autodl-fs/data/CrisisKan/crisismmd_dataset.py", line 133, in initialize
    self.read_data(ann_file)
  File "/autodl-fs/data/CrisisKan/crisismmd_dataset.py", line 79, in read_data
    event_name, tweet_id, image_id, tweet_text, image,  label, final_text, trigger_words = l.split(
ValueError: too many values to unpack (expected 8)`
The parameters you read from the database file do not match the column names of the file itself. The last two parameters in the program are `final_text ，trigger_words`, while in the database they are `label_text, label_image, and label_text_image`. I also saw that you wrote them in the comments, but I cannot understand your parameters and their meanings. I hope you can answer my questions.

**Comment by li-shuang-git** [comment]
I noticed that you have recently modified the crisismmd_dataset.py file, but there are still a few issues in it.

1. You have replaced `final-text, trigger_words` with` label_text, label_image, and label_text_image`, but the variable `final-text` continues to appear in the following code.
2. In terms of the types of tasks to be executed, three concepts related to task 2, task2_merged, and task2_full, appear in the crisimmd_dataset.py file, and there are serious inconsistencies between them.
I hope you can answer my questions.

**Comment by shubhamgpt007** [comment]
Hi, 
Thanks for reporting the issues. I have updated the crisismmd_dataset.py file. But for the _final_text,_ you need to first run wiki.py and generate the extended text from there that will be used throughout the program.
